[consumer]
topic = ""

[kafka]
"bootstrap.servers" = ""
"group.id" = ""
"security.protocol" = "SASL_SSL"
"sasl.mechanisms" = "PLAIN"
"sasl.username" = ""
"sasl.password" = ""

# Best practice for higher availability in librdkafka clients prior to 1.7
"session.timeout.ms" = 45000

"client.id" = ""

"auto.offset.reset" = "earliest"
"enable.auto.commit" = true


