[plugin]
processor = "cmip6"

[consumer]
topic = "CMIP6"

[kafka]
"bootstrap.servers" = "localhost:39092"
"group.id" = "piddiplatsch-consumer"
"auto.offset.reset" = "earliest"
"enable.auto.commit" = true

[handle]
server_url = "http://localhost:8000"
prefix = "21.TEST"
username = "testuser"
password = "testpass"
