[plugin]
processor = "cmip6"

[consumer]
topic = "CMIP6"
retry_topic = "CMIP6"
output_dir = "outputs"
stats_summary_interval = 100

[kafka]
"bootstrap.servers" = "localhost:39092"
"group.id" = "piddiplatsch-001"
"auto.offset.reset" = "earliest"
"enable.auto.commit" = true

[handle]
server_url = "http://localhost:8000"
prefix = "21.TEST"
username = "300:21.TEST/testuser"
password = "testpass"

[stac]
base_url = "https://api.stac.esgf.ceda.ac.uk"
timeout = 10

[cmip6]
landing_page_url = "https://handle-esgf.dkrz.de/lp"
max_parts = -1
excluded_asset_keys = ["reference_file", "globus", "thumbnail", "quicklook"]
